<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by www.codechief.org</title>
</head>
<body>

    <div >
        <div id="header" style="background-color:#5acaf6;color:white;padding:0 auto;">
        <img style="vertical-align:middle;" src="https://img.icons8.com/color/48/4a90e2/large-icons.png"/><h1 style="display: inline-block;vertical-align:middle;">Qr-code Attendance</h1>
        </div>
        <div id="body" style="background-color:#93cce9;color:black;padding:10px;">
           <p style="font-size: 25px;font-weight:bold;">Welcome Student,<br>
            You're almost done!</p>
            <div>
                <p style="color:white;font-size:18px;">This is your verification code to create your account!</p>
                <center><h1 style="background-color: #6a8781;color:white;">{{ $verify_number }}</h1></center>
            </div>
            <p style="padding-bottom:10px;">Thank you,<br>    
               qr-code attendence system
            </p>
        </div>
 
   
    </div>
</body>
</html> 